# IMPORTANT: This file was generated by Cucumber 0.4.4
# Edit at your own peril - it's recommended to regenerate this file
# in the future when you upgrade to a newer version of Cucumber.
# Consider adding your own code to a new file instead of editing this one.
require 'logger'
require 'cucumber'
require 'broach'
# Comment out the next line if you don't want Cucumber Unicode support
require 'cucumber/formatter/unicode'
# require 'cucumber/webrat/element_locator' # Lets you do table.diff!(element_at('#my_table_or_dl_or_ul_or_ol').to_table)
# require 'cucumber/rails/rspec'
require 'test/unit/assertions'
include Test::Unit::Assertions


=begin
require 'webrat'
require 'webrat/core/matchers'

Webrat.configure do |config|
  config.mode = :rails
  config.open_error_files = false # Set to true if you want error pages to pop up in the browser
end
=end

if ENV['SAFARIWATIR']
  require 'safariwatir'
  Browser = Watir::Safari
  browser = Browser.new
elsif ENV['FIREWATIR']
  require "rubygems"
  require "watir-webdriver" 
  browser = Watir::Browser.new(:firefox) 
elsif ENV['CHROMEWATIR']
  require 'chrome_watir'
  Browser = ChromeWatir::Browser
  browser = Browser.new
else
  case RUBY_PLATFORM
  when /darwin/
    require 'firewatir'
    Browser = FireWatir::Firefox
    browser = Browser.new
  when /win32|mingw/
    require 'watir'
    require 'win32ole'
    Browser = Watir::IE
    browser = Browser.new
    browser.speed = :fast
  when /java/
    require 'celerity'
    Browser = Celerity::Browser
    browser = Browser.new
  else
    raise "This platform is not supported (#{PLATFORM})"
  end
end


Before do
  @browser = browser
  @random = rand(9999999).to_s
  @arch= "http://architecturenergy.com"
end
